# version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: nexcart-postgres
    environment:
      POSTGRES_USER: nexcart
      POSTGRES_PASSWORD: nexcart123
      POSTGRES_DB: nexcart_users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - nexcart-network

  mongodb:
    image: mongo:6
    container_name: nexcart-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: nexcart
      MONGO_INITDB_ROOT_PASSWORD: nexcart123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
    - nexcart-network

  redis:
    image: redis:7-alpine
    container_name: nexcart-redis
    ports:
      - "6399:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
    - nexcart-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: nexcart-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
    - nexcart-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: nexcart-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: nexcart-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
    - nexcart-network

  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: nexcart-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
    - nexcart-network
  minio:
    image: minio/minio:latest
    container_name: nexcart-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: nexcart
      MINIO_ROOT_PASSWORD: nexcart123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
    - nexcart-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: nexcart-gateway
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - postgres
      - mongodb
    restart: unless-stopped
    networks:
    - nexcart-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: nexcart-jaeger
    ports:
      - "16686:16686"   # Jaeger UI
      - "6831:6831/udp" # Jaeger agent (receives traces)
      - "4318:4318"     # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    networks:
    - nexcart-network

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    container_name: nexcart-user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - SERVICE_NAME=user-service
    env_file:
    - ./shared/.env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - nexcart-network

  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
    container_name: nexcart-product-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - SERVICE_NAME=product-service
    env_file:
      - ./shared/.env
    depends_on:
      - mongodb
      - kafka
    restart: unless-stopped
    networks:
      - nexcart-network

  cart-service:
    build:
      context: .
      dockerfile: services/cart-service/Dockerfile
    container_name: nexcart-cart-service
    ports:
      - "3003:3003"
    env_file:
      - ./shared/.env
    environment:
      - SERVICE_NAME=cart-service
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - nexcart-network

  inventory-service:
    build:
      context: .
      dockerfile: services/inventory-service/Dockerfile
    container_name: nexcart-inventory-service
    ports:
      - "3004:3004"
    env_file:
      - ./shared/.env
    environment:
      - SERVICE_NAME=inventory-service
    depends_on:
      - postgres
      - kafka
    restart: unless-stopped
    networks:
      - nexcart-network

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    container_name: nexcart-order-service
    ports:
      - "3005:3005"
    env_file:
      - ./shared/.env
    environment:
      - SERVICE_NAME=order-service
    depends_on:
      - postgres
      - kafka
    restart: unless-stopped
    networks:
      - nexcart-network

  payment-service:
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile
    container_name: nexcart-payment-service
    ports:
      - "3006:3006"
    env_file:
      - ./shared/.env
    environment:
      - SERVICE_NAME=payment-service
    depends_on:
      - postgres
      - kafka
    restart: unless-stopped
    networks:
      - nexcart-network

  search-service:
    build:
      context: .
      dockerfile: services/search-service/Dockerfile
    container_name: nexcart-search-service
    ports:
      - "3007:3007"
    env_file:
      - ./shared/.env
    environment:
      - SERVICE_NAME=search-service
    depends_on:
      - elasticsearch
      - kafka
    restart: unless-stopped
    networks:
      - nexcart-network

  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    container_name: nexcart-notification-service
    ports:
      - "3008:3008"
    env_file:
      - ./shared/.env
    environment:
      - SERVICE_NAME=notification-service
    depends_on:
      - postgres
      - kafka
    restart: unless-stopped
    networks:
      - nexcart-network

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  minio_data:
  es_data:

networks:
  nexcart-network:
    driver: bridge
